[package]
name = "soez_core"
version = "0.1.0"
authors = ["TalGl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
specs = "0.15.1"