name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      working-directory: ./soez_game
      env:
        RUST_BACKTRACE: full
      run: cargo build --verbose
      
    - name: upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name:  build
        path: target/debug/build

    - name: Run tests
      working-directory: ./soez_game
      run: cargo test --verbose
