name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: ./soez_game
      env:
        RUST_BACKTRACE: 1
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./soez_game
      run: cargo test --verbose
