name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install prerequisites
      run: sudo apt update && sudo apt-get install -y --fix-missing xorg-dev libglu1-mesa-dev

    - name: build
      working-directory: ./soez_game
      env:
        RUST_BACKTRACE: full
      run: cargo build --release --verbose
      
    - name: generate docs
      working-directory: ./soez_game
      run: cargo doc --target-directory target/doc
      
    - name: upload docs
      uses: actions/upload-artifact@v1
      with:
        name:  target
        path: ./soez_game/target/doc

    - name: test
      working-directory: ./soez_game
      run: cargo test --verbose
